### ISSUE TITLE
Default date

### ISSUE THREAD

**Issue by pinkeshkamdar** [YD-Feng/dateTimePicker#2]
There is no function or option to set current date time as default date on page load.

**Comment by YD-Feng** [comment]
<input type="text" class="mt10px input" id="J-demo-03" value="2017-03-15 12:00:00">

<script type="text/javascript">
$('#J-demo-03').dateTimePicker({
    mode: 'dateTime'
});
</script>

**Comment by YD-Feng** [comment]
<input type="text" class="mt10px input" id="J-demo-03" value="2017-03-15 12:00:00">

**Comment by YD-Feng** [comment]
Set the default value to the value attribute of the input element. And you can find this in "demo/index.html"
